### PR TITLE
Added Pi 3 B+ support, compatibility with legacy examples, fixed rst readme

### PR DESCRIPTION
**Pull request by Gadgetoid**

### CODE REVIEW

**Comment by Gadgetoid** [comment]
This is a complete suite of changes representing a version of rpi_ws218x-python that I believe is well positioned to take over from the code in the upstream rpi_ws281x repository.

I have pushed this out as 3.1.0, with Python wheels for 2.7, 3.4 and 3.5 on the Raspberry Pi: https://pypi.org/project/rpi_ws281x/

**Comment by Gadgetoid** [comment]
@penfold42 I need write access to merge this, please ;)

**Comment by penfold42** [comment]
Collaborator ?

**Comment by Gadgetoid** [comment]
Bingo! Thank you.

**Pull request merged**
